name: Update protobuf definitions
on: workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v3
        name: Set up Go 1.18.4
        with:
          go-version: '1.18.4'
          check-latest: true
      - name: Update protobuf definitions
        run: |
          ./scripts/installProtoc.sh
          
          git submodule update --remote --recursive
          ./scripts/updateProtos.sh
          
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -am "build: update protobuf definitions"
          git push